name: API Automation CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Force Install and Run
        run: |
          pip install flask requests pytest pytest-html
          python server.py &
          sleep 10
          pytest
